/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginForm.java
 *
 * Created on Dec 8, 2011, 10:46:36 AM
 */

package com.forms;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import org.netbeans.validation.api.Problem;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;

import com.dao.UserDAO;
import com.helper.UserSession;
import com.model.UserModel;
import java.awt.event.KeyEvent;
import swinghelper.OptionHelper;
import swinghelper.StringHelper;

/**
 *
 * @author Admin
 */
public class LoginForm extends javax.swing.JFrame {
 ValidationGroup vg;
    /** Creates new form LoginForm */
    public LoginForm() {
        initComponents();
        swinghelper.SwingUtilities.setScreenCenter(this);

          vg= validationPanel1.getValidationGroup();
       //vg.add(jTextField1, ValidationStrategy.DEFAULT, null)
 vg.add(jTextField2, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.NO_WHITESPACE);

 vg.add(jPasswordField1, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.NO_WHITESPACE);
        
    }

    public boolean performLogin() throws HeadlessException {
        // TODO add your handling code here:
        Problem p = vg.validateAll();
        String msg = "";
        if (p != null) {
            msg = p.getMessage();
        }
        System.out.println("msg " + msg);
        if (msg.length() == 0) {
            UserModel um = new UserModel();
            um.setLoginId(jTextField2.getText());
            um.setUserPassword(jPasswordField1.getText());
            um = new UserDAO().CheckIDandPassword(um);
            if (um != null) {
                if(um!=null&&um.getActiveFlag().equalsIgnoreCase("2")){
                    JOptionPane.showMessageDialog(this, "You are blocked by administrator!!!");
                    return false;
                }
               

                    UserSession.loggedInUser = um;
                int di=StringHelper.nullObjectToIntegerEmpty(um.getDays());
                if(um.getDays()==null||di>15 ){
                    OptionHelper.showMessage("You are logging in for the first time. YOu need to change your password.");

                    ChangePassword cp=new ChangePassword();
                    cp.setVisible(true);
                    return false;

                }


            
                this.setVisible(false);
                new MainForm().setVisible(true);
            } else {
                if(um==null){
                    JOptionPane.showMessageDialog(this, "Login id or password may be incorrect !!!");

                }if(um!=null&&um.getActiveFlag().equalsIgnoreCase("2")){
                    JOptionPane.showMessageDialog(this, "You are blocked by administrator!!!");

                }
                return true;
            }
        }
        return false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        validationPanel1 = new org.netbeans.validation.api.ui.ValidationPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(LoginForm.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(440, 214));
        setResizable(false);
        getContentPane().setLayout(null);

        validationPanel1.setBackground(java.awt.SystemColor.window);
        validationPanel1.setName("validationPanel1"); // NOI18N
        getContentPane().add(validationPanel1);
        validationPanel1.setBounds(120, 180, 278, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14));
        jLabel2.setText("Login Name");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 60, 94, 27);

        jTextField2.setName("Login Name"); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 70, 101, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14));
        jLabel3.setText("Password");
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 100, 94, 27);

        jPasswordField1.setName("Password "); // NOI18N
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(210, 110, 101, 20);

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12));
        jButton2.setText("Login");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 140, 69, 25);

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12));
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 140, 87, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_large.jpg"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 440, 220);

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14));
        jLabel5.setText("Login Name");
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 60, 94, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      performLogin();
     jButton2.setEnabled(true);
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new RegistrationForm().setVisible(true);


            }
        });

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        // TODO add your handling code here:
     


    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
           System.out.println(" evt.getKeyCode() "+evt.getKeyCode());
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
performLogin();
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                    //     UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
                //    UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                //     UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");

                    // swinghelper.SwingUtilities.applyLiquidtheme();
                    new LoginForm().setVisible(true);
             
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private org.netbeans.validation.api.ui.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables

}
