/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on Jan 1, 2002, 1:28:51 PM
 */

package com.forms;

import com.helper.*;

import java.awt.BorderLayout;
import org.jdesktop.application.Action;
import org.openide.util.Exceptions;


/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
              swinghelper.SwingUtilities.setScreenCenter(this);
              fileMenu.setText("File");
              jMenu1.setText("Distributor");
              jMenu2.setText("Admin");
              jMenuItem1.setText("Upload Files");
              setExtendedState(MAXIMIZED_BOTH);
              if(UserSession.loggedInUser.getRollId().equalsIgnoreCase(Constants.DISTRIBUTOR_ROLL_ID)){ //Distributor
                jMenu3.setVisible(false); // Agent
                jMenu2.setVisible(false);   // Admin
                jMenu1.setVisible(true);    // distributor
              }else if(UserSession.loggedInUser.getRollId().equalsIgnoreCase(Constants.AGENT_ROLL_ID)){ //Distributor
                jMenu3.setVisible(true); // Agent
                jMenu2.setVisible(false);   // Admin
                jMenu1.setVisible(false);    // distributor
              }else if(UserSession.loggedInUser.getRollId().equalsIgnoreCase(Constants.ADMIN_ROLL_ID)){ //Distributor
                jMenu3.setVisible(true); // Agent
                jMenu2.setVisible(true);   // Admin
                jMenu1.setVisible(true);    // distributor
              }

              
    }

    public void logout() {
        // TODO add your handling code here:
        UserSession.loggedInUser = null;
        this.setVisible(false);
        LoginForm lf=new LoginForm();
        lf.setVisible(true);
//        System.exit(0);
    }
    
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        helpMenu2 = new javax.swing.JMenu();
        helpMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(MainForm.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(950, 662));

        desktopPane.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        desktopPane.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        desktopPane.setForeground(new java.awt.Color(0, 0, 0));
        desktopPane.setToolTipText(resourceMap.getString("desktopPane.toolTipText")); // NOI18N
        desktopPane.setFont(resourceMap.getFont("desktopPane.font")); // NOI18N
        desktopPane.setName(resourceMap.getString("desktopPane.name")); // NOI18N
        desktopPane.setPreferredSize(new java.awt.Dimension(950, 662));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img03.png"))); // NOI18N
        jLabel1.setBounds(20, 10, 500, 460);
        desktopPane.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setFont(resourceMap.getFont("desktopPane.font")); // NOI18N
        jPanel1.setName("PanelBottom"); // NOI18N

        statusLabel.setText("Done");

        jProgressBar1.setFont(resourceMap.getFont("desktopPane.font")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jProgressBar1.getAccessibleContext().setAccessibleName("");
        jProgressBar1.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setBounds(0, 610, -1, -1);
        desktopPane.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanel1.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N
        jPanel1.getAccessibleContext().setAccessibleDescription("Status Panel");

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);
        desktopPane.getAccessibleContext().setAccessibleName(resourceMap.getString("desktopPane.AccessibleContext.accessibleName")); // NOI18N
        desktopPane.getAccessibleContext().setAccessibleDescription(resourceMap.getString("desktopPane.AccessibleContext.accessibleDescription")); // NOI18N

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setText("Distributor");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("View Shared Files");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        menuBar.add(jMenu1);

        jMenu3.setText("Agent");

        jMenuItem4.setText("Agent Requests");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem6.setText("Agent Downloads");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        menuBar.add(jMenu3);

        jMenu2.setText("Admin");

        jMenuItem3.setText("Configure App");
        jMenu2.add(jMenuItem3);

        jMenuItem2.setText("Probability Calculations");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem7.setText("Manage Agents");
        jMenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem7MouseClicked(evt);
            }
        });
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        menuBar.add(jMenu2);

        helpMenu2.setText("Change Password");
        helpMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenu2MouseClicked(evt);
            }
        });
        helpMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenu2ActionPerformed(evt);
            }
        });
        menuBar.add(helpMenu2);

        helpMenu1.setText("Logout");
        helpMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenu1MouseClicked(evt);
            }
        });
        helpMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenu1ActionPerformed(evt);
            }
        });
        menuBar.add(helpMenu1);

        setJMenuBar(menuBar);

        getAccessibleContext().setAccessibleDescription(resourceMap.getString("AccessibleContext.accessibleDescription")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            uploadFiles();
            // TODO add your handling code here:
//                SearchForm wi=new SearchForm();
// desktopPane.setLayout(new BorderLayout());
//desktopPane.add(wi,BorderLayout.CENTER);
//wi.setVisible(true);
//wi.repaint();
        } catch (Exception ex) {
           ex.printStackTrace();;
        }

        // TODO add your handling code here:

//                SearchForm wi=new SearchForm();
// desktopPane.setLayout(new BorderLayout());
//desktopPane.add(wi,BorderLayout.CENTER);
//wi.setVisible(true);
//wi.repaint();


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            // TODO add your handling code here:
            AgentRequests wi = new AgentRequests();
            wi.setSize(300, 300);
            desktopPane.setLayout(new BorderLayout());
            desktopPane.add(wi, BorderLayout.CENTER);
            wi.setVisible(true);
            wi.repaint();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            // TODO add your handling code here:
            ViewSharedFiles wi = new ViewSharedFiles();
            wi.setSize(300, 300);
            desktopPane.setLayout(new BorderLayout());
            desktopPane.add(wi, BorderLayout.CENTER);
            wi.setVisible(true);
            wi.repaint();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
             try {
            // TODO add your handling code here:
            AgentDownload wi = new AgentDownload();
            wi.setSize(300, 300);
            desktopPane.setLayout(new BorderLayout());
            desktopPane.add(wi, BorderLayout.CENTER);
            wi.setVisible(true);
            wi.repaint();
            
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void helpMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenu1ActionPerformed
        logout();

    }//GEN-LAST:event_helpMenu1ActionPerformed

    private void helpMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenu1MouseClicked
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_helpMenu1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
            ProbabilityCalculations wi = new ProbabilityCalculations();
            wi.setSize(300, 300);
            desktopPane.setLayout(new BorderLayout());
            desktopPane.add(wi, BorderLayout.CENTER);
            wi.setVisible(true);
            wi.repaint();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }

        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void helpMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenu2MouseClicked
        // TODO add your handling code here:
            ChangePassword  wi=new ChangePassword();
 wi.setVisible(true);
    }//GEN-LAST:event_helpMenu2MouseClicked

    private void helpMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenu2ActionPerformed
        // TODO add your handling code here:
      

    }//GEN-LAST:event_helpMenu2ActionPerformed

    private void jMenuItem7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MouseClicked
       
    }//GEN-LAST:event_jMenuItem7MouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
   try {
            // TODO add your handling code here:
            UserManamgement wi = new UserManamgement();
            wi.setSize(300, 300);
            desktopPane.setLayout(new BorderLayout());
            desktopPane.add(wi, BorderLayout.CENTER);
            wi.setVisible(true);
            wi.repaint();
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    public  void setStatus(String message){
        statusLabel.setText(message);
    }
    public  void startProgressBar(){
        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setVisible(true);
    }

    public  void stopProgressBar(){
        jProgressBar1.setIndeterminate(false);
        jProgressBar1.setVisible(true);
    }




    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainForm().setVisible(true);
            

            }
        });
    }

    @Action
    public void uploadFiles() throws Exception {
    UploadFiles  wi=new UploadFiles();
    wi.setSize(300, 300);
 desktopPane.setLayout(new BorderLayout());
desktopPane.add(wi,BorderLayout.CENTER);
wi.setVisible(true);
wi.repaint();


    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenu helpMenu2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

}
