/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistrationForm.java
 *
 * Created on Jan 22, 2010, 9:36:08 AM
 */

package com.forms;

import java.awt.Cursor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import org.netbeans.validation.api.Problem;
import org.netbeans.validation.api.Problems;
import org.netbeans.validation.api.Validator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.openide.util.Exceptions;
import com.dao.UserDAO;

import com.helper.GetSetProperties;
import com.helper.SimpleCrypto;

import swinghelper.SwingUtilities;


/**
 *
 * @author admin
 */
public class RegistrationForm extends javax.swing.JFrame {
 ValidationGroup vg;
    /** Creates new form RegistrationForm */
    public RegistrationForm() {
        initComponents();
              swinghelper.SwingUtilities.setScreenCenter(this);
            btnUpdate.setVisible(false);
                  vg= validationPanel1.getValidationGroup();
       //vg.add(jTextField1, ValidationStrategy.DEFAULT, null)
 vg.add(txtFName, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.NO_WHITESPACE);
 vg.add(txtLName, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.NO_WHITESPACE);
 
  vg.add(txtCellNo, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.minLength(10));

  vg.add(txtEmailAddr, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.EMAIL_ADDRESS);

    vg.add(txtLoginId, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.NO_WHITESPACE);
 
      vg.add(jPasswordField1, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.NO_WHITESPACE);
      vg.add(jPasswordField2, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.NO_WHITESPACE);
          vg.add(txtEmailAddr1, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.NO_WHITESPACE);

       vg.add(txtEmailAddr2, Validators.REQUIRE_NON_EMPTY_STRING,
          Validators.NO_WHITESPACE);
              vg.add(jPasswordField2, new CustomPasswordMatchValidator());
        try {
            this.setIconImage(ImageIO.read(this.getClass().getResource("/img/Accept-Male-User128.png")));
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }

    }
        public class CustomPasswordMatchValidator implements Validator<String> {

        public boolean validate(Problems problems, String compName, String model) {
            boolean result = jPasswordField1.getText().equals(jPasswordField2.getText());
            if (!result) {
                String message = "Password and confirm password do not match!";
                problems.add(message);
            }
            return result;

        }
    }
    public static boolean FLAG = true;
    UserDAO userdao = new UserDAO();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCellNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmailAddr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmailAddr1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmailAddr2 = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        validationPanel1 = new org.netbeans.validation.api.ui.ValidationPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLoginId = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("User Registration Form");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(747, 421));
        getContentPane().setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(RegistrationForm.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("RegistrationFormFont"))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Verdana", 0, 10));

        jLabel2.setFont(resourceMap.getFont("RegistrationFormFont")); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(resourceMap.getFont("RegistrationFormFont")); // NOI18N
        jLabel3.setText("Last Name");

        txtFName.setFont(new java.awt.Font("Lucida Sans", 2, 14));
        txtFName.setName("First Name"); // NOI18N
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        txtLName.setFont(new java.awt.Font("Lucida Sans", 2, 14));
        txtLName.setName("Last Name"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("RegistrationFormFont")); // NOI18N
        jLabel5.setText("Cell Number");

        txtCellNo.setFont(new java.awt.Font("Lucida Sans", 2, 14));
        txtCellNo.setName("Cell Number"); // NOI18N
        txtCellNo.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((Character.isDigit(c) ||(c == KeyEvent.VK_PLUS)||
                    (c == KeyEvent.VK_BACK_SPACE) ||
                    (c == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            e.consume();
        }
    }
    });

    jLabel9.setFont(resourceMap.getFont("RegistrationFormFont")); // NOI18N
    jLabel9.setText("Email Address");

    txtEmailAddr.setFont(new java.awt.Font("Lucida Sans", 2, 14));
    txtEmailAddr.setName("Email Address"); // NOI18N

    jLabel10.setFont(new java.awt.Font("Verdana", 0, 12));
    jLabel10.setText("City");

    txtEmailAddr1.setFont(new java.awt.Font("Lucida Sans", 2, 14));
    txtEmailAddr1.setName("Email Address"); // NOI18N

    jLabel11.setFont(new java.awt.Font("Verdana", 0, 12));
    jLabel11.setText("Pincode");

    txtEmailAddr2.setFont(new java.awt.Font("Lucida Sans", 2, 14));
    txtEmailAddr2.setName("Email Address"); // NOI18N

    org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPanel1Layout.createSequentialGroup()
            .add(22, 22, 22)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                    .add(txtEmailAddr2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(txtEmailAddr1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createSequentialGroup()
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel3)
                                .add(jLabel2)
                                .add(jLabel5))
                            .add(65, 65, 65))
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, txtLName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, txtFName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, txtCellNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, txtEmailAddr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
            .add(358, 358, 358))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(txtFName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel2))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(txtLName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel3))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(txtCellNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel5))
            .add(7, 7, 7)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(txtEmailAddr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(txtEmailAddr1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(txtEmailAddr2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    getContentPane().add(jPanel1);
    jPanel1.setBounds(10, 30, 352, 203);

    btnRegister.setFont(new java.awt.Font("Verdana", 0, 10));
    btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-to-database16.png"))); // NOI18N
    btnRegister.setText("Register");
    btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnRegisterMouseClicked(evt);
        }
    });
    btnRegister.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRegisterActionPerformed(evt);
        }
    });
    getContentPane().add(btnRegister);
    btnRegister.setBounds(130, 380, 99, 25);

    btnUpdate.setFont(new java.awt.Font("Verdana", 0, 10));
    btnUpdate.setText("Update");
    btnUpdate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnUpdateActionPerformed(evt);
        }
    });
    getContentPane().add(btnUpdate);
    btnUpdate.setBounds(240, 380, 73, 23);
    getContentPane().add(validationPanel1);
    validationPanel1.setBounds(10, 420, 340, 30);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("RegistrationFormFont"))); // NOI18N

    jLabel6.setFont(resourceMap.getFont("RegistrationFormFont")); // NOI18N
    jLabel6.setText("Login Id");

    jLabel7.setFont(resourceMap.getFont("RegistrationFormFont")); // NOI18N
    jLabel7.setText("Password");

    jLabel8.setFont(resourceMap.getFont("RegistrationFormFont")); // NOI18N
    jLabel8.setText("Confirm Password");

    txtLoginId.setFont(new java.awt.Font("Lucida Sans", 2, 14));
    txtLoginId.setName("Login Id"); // NOI18N

    org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
            .add(37, 37, 37)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jLabel6)
                .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .add(jLabel8))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPasswordField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .add(jPasswordField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .add(txtLoginId, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2Layout.createSequentialGroup()
                    .add(jLabel6)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                    .add(jLabel7))
                .add(jPanel2Layout.createSequentialGroup()
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(28, 28, 28)
                            .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(txtLoginId)
                            .add(38, 38, 38)))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jPasswordField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel8))))
            .addContainerGap())
    );

    getContentPane().add(jPanel2);
    jPanel2.setBounds(10, 240, 352, 132);

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registration.jpg"))); // NOI18N
    getContentPane().add(jLabel1);
    jLabel1.setBounds(150, 30, 580, 360);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtFNameActionPerformed

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        try {

                    Problem p = vg.validateAll();

        String msg = "";
        if (p != null) {   
            msg = p.getMessage();
            validationPanel1.show(true);
        }
        System.out.println("msg " + msg);
        if (msg.length() == 0) {

            // TODO add your handling code here:
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String firstName = txtFName.getText();
            String lastName = txtLName.getText();
            long cellNo = Long.parseLong(txtCellNo.getText());
            String emailId = txtEmailAddr.getText();
            String loginID = txtLoginId.getText();
            String city=txtEmailAddr1.getText();
            String pincode=txtEmailAddr2.getText();
            String password = SimpleCrypto.encrypt(GetSetProperties.getProperty("SEED_KEY"),jPasswordField1.getText());
            boolean success = userdao.AddUser(loginID, password, 0, firstName, lastName, cellNo, emailId,city,pincode);
            if (success) {
                JOptionPane.showMessageDialog(this, "User Registered Successfully!!");
                this.setVisible(false);

      
            }
            }
            this.setCursor(Cursor.getDefaultCursor());
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
     
    }
}//GEN-LAST:event_btnRegisterMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
//        int userID = Integer.parseInt(txtUserId.getText());
        String firstName = txtFName.getText();
        String lastName = txtLName.getText();
        //String IPAdd = txtIpAddr.getText();
        long cellNo =Long.parseLong(txtCellNo.getText());
        String emailId = txtEmailAddr.getText();
        String loginID = txtLoginId.getText();
        String password = jPasswordField1.getText();
//        try {
//            userdao.UpdateUser(loginID, password, 0, firstName, lastName, cellNo, emailId);
//        } catch (UnknownHostException ex) {
//            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed
  

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField txtCellNo;
    private javax.swing.JTextField txtEmailAddr;
    private javax.swing.JTextField txtEmailAddr1;
    private javax.swing.JTextField txtEmailAddr2;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtLoginId;
    private org.netbeans.validation.api.ui.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables

}
